routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersController;


Auth::routes(
    [ //php artisan route:clear
        'verify'          => true, //attiva l'email di verifica se clicci nell'email che arriva su mailtrap l'account di verifica risulterà attivo su SQL
        // 'register'       => true, //attiva la registrazione
        // 'reset'          => false,
    ] );

Route::get('/', 'SiteController@index')->name('home');

Route::get('/contact-us', 'SiteController@contacts')->name('contacs-us');

Route::get('/entity/{id}/{name}/{filter?}', 'SiteController@test'); // scrivili nella barra del browser il punto interrogativo sta come opzionale

// Route::resource('movies', 'Admin\AdminMoviesController'); //O cosi' nel secondo parametro è già impostata la cartella controllers

Route::prefix('admin-movies-managment')->namespace('Admin')->name('admin.')->middleware('can:can-admin')->group( function ()
{
    Route::resource('movies', 'AdminMoviesController'); // in AdminMoviesManagmetn hai le funzioni pubblice, create,show,destroy. Il metodo resource crea quelle rotte
});


Route::prefix('admin-users-managment')->namespace('Admin')->name('admin.')->middleware('can:can-admin')->group( function () // per poter utilizzare can-admin devi andare in authserviceprovider nella cartella providers
{
    Route::resource('user', 'AdminUserController')->except(['create','store']);
    Route::get('user/{user}/restore','AdminUserController@restore')->name('user.restore');
});


Route::get('/test', 'TestController@index')->middleware('verified');

Route::get('/profile', 'UsersController@profile')->name('profile');
Route::patch('/update-profile', 'UsersController@profileUpdate')->name('update-profile');
Route::delete('/delete-profile', 'UsersController@deleteProfile')->name('delete-profile');

resources/views/partials/admin-header.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{{route('admin.user.index')}}">List Utenti</a></li>
                    <li><a href="{{route('admin.movies.index')}}">List Film</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </li>
        </ul>
    </div><!-- /.container-fluid -->
</nav>

resources/views/partials/header.blade.php
<header id="header" class="bg-dark-blue">
        <div id="logo">
            <img  style=" width: auto; height:100%;" src="{{ asset('./immagini/logo.png') }}" alt="">
        </div>
        <nav id="main-menu">
            <ul>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m"><i class="fas fa-film"></i><a href="/">Film</a></div></div>
                </li>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m"><div class="separator"></div></div></div>
                </li>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m"><i class="fas fa-film"></i><a href="/">Sale</a></div></div>
                </li>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m"><div class="separator"></div></div></div>
                </li>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m"><i class="fas fa-film"></i><a href="/">Prenotazioni</a></div></div>
                </li>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m"><div class="separator"></div></div></div>
                </li>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m"><i class="fas fa-film"></i><a href="/">Contatti</a></div></div>
                </li>

            </ul>
        </nav>
        <div id="secondary-menu" class="bg-dark-blue">
            <ul>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m">
                    <!-- così levi il login al login -->
                        @guest
                            <a href="{{route( 'login') }}"class="mv-header-btn">login</a>
                        @else
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();"
                                                class="mv-header-btn">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        @endguest
                    <!-- così levi il login al login -->
                    </div></div><!-- la schermata di login è quella predefinita di Larael -->
                </li>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m"><div class="separator"></div></div></div>
                </li>
                <li>
                    <div class="w-full h-full dt"><div class="dtc va-m"><i class="fas fa-film"></i></div></div>
                </li>
            </ul>
        </div>
    </header>