routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersController;


Auth::routes(
    [ //php artisan route:clear
        'verify'          => true, //attiva l'email di verifica se clicci nell'email che arriva su mailtrap l'account di verifica risulterà attivo su SQL
        // 'register'       => true, //attiva la registrazione
        // 'reset'          => false,
    ] );

Route::get('/', 'SiteController@index')->name('home');

Route::get('/contact-us', 'SiteController@contacts')->name('contacs-us');

Route::get('/entity/{id}/{name}/{filter?}', 'SiteController@test'); // scrivili nella barra del browser il punto interrogativo sta come opzionale

// Route::resource('movies', 'Admin\AdminMoviesController'); //O cosi' nel secondo parametro è già impostata la cartella controllers

Route::prefix('admin-movies-managment')->namespace('Admin')->name('admin.')->middleware('can:can-admin')->group( function ()
{
    Route::resource('movies', 'AdminMoviesController'); // in AdminMoviesManagmetn hai le funzioni pubblice, create,show,destroy. Il metodo resource crea quelle rotte
});


Route::prefix('admin-users-managment')->namespace('Admin')->name('admin.')->middleware('can:can-admin')->group( function () // per poter utilizzare can-admin devi andare in authserviceprovider nella cartella providers
{
    Route::resource('user', 'AdminUserController')->except(['create','store']);
    Route::get('user/{user}/restore','AdminUserController@restore')->name('user.restore');
});


Route::get('/test', 'TestController@index')->middleware('verified');

Route::get('/profile', 'UsersController@profile')->name('profile');
Route::patch('/update-profile', 'UsersController@profileUpdate')->name('update-profile');
Route::delete('/delete-profile', 'UsersController@deleteProfile')->name('delete-profile');

app/Http/Controllers/MoviesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MoviesController extends Controller
{
    //
}

resources/views/admin/movies/create.blade.php
@extends('layouts.admin-app')
@section('content')
            <div class="container">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <!-- @include('components.message') -->
                <div class="row">
                    <div class="col-xs-12">
                        <form method="POST" action="{{route('admin.movies.store')}}" enctype="multipart/form-data"> <!-- enctype="multipart/form-data" per fargli recepire i file -->
                            @csrf

                            <div class="form-group @error('name') has-error @enderror">
                                <label class="control-label" for="movie-title">{{ __('labels.create_form.movie_name') }}</label>
                                <input type="text" class="form-control" id="movie-title" name="name" value="{{old('name') ? old('name') : ' '}}">
                                @if($errors->has('name'))
                                    <span class="help-block">{{$errors->first('name')}}</span>
                                @endif
                            </div>

                            <div class="form-group  @error('code') has-error @enderror">
                                <label class="control-label" for="movie-code">{{ __('labels.create_form.movie_code') }}</label>
                                <input type="text" class="form-control" id="movie-code" name="code" value="{{old('code') ? old('code') : ' '}}">
                                @if($errors->has('code'))
                                    <span class="help-block">{{$errors->first('code')}}</span>
                                @endif
                            </div>
                            <div class="form-group  @error('duration') has-error @enderror">
                                <label class="control-label" for="movie-duration">{{ __('labels.create_form.movie_duration') }}</label>
                                <input type="text" class="form-control" id="movie-duration" name="duration" value="{{old('duration') ? old('duration') : ' '}}">
                                @if($errors->has('duration'))
                                    <span class="help-block">{{$errors->first('duration')}}</span>
                                @endif
                            </div>

                            <div class="form-group  @error('cover_path') has-error @enderror">
                                <label class="control-label" for="movie-cover">{{ __('labels.create_form.movie_cover') }}</label>
                                <input type="file" class="form-control" id="movie-cover" name="cover_path" value="{{old('cover_path') ? old('cover_path') : ' '}}">
                                <!-- <input type="text" class="form-control" id="movie-cover" name="cover_path" value="{{old('cover_path') ? old('cover_path') : ' '}}"> -->
                                @if($errors->has('cover_path'))
                                    <span class="help-block">{{$errors->first('cover_path')}}</span>
                                @endif
                            </div>
                            <!-- Se te ne serve solo 1
                            <div class="form-group @error('category_id') has-error @enderror">
                                <label class="control-label" for="category_id">{{ __('labels.create_form.category') }}</label>
                                     Primo parametro name del form,secondo parametro array chiave valore, terzo parametro fregatene,c'era messo null
                                {{ Form::select('category_id', $categories_select,null,['placeholder'=>'Selezionare una categorie','class'=>'form-control', 'id'=>'category_id'])}}
                                @if($errors->has('category_id'))
                                    <span class="help-block">{{$errors->first('category_id')}}</span>
                                @endif
                            </div>
                            -->

                            <!-- se te ne servono di piu -->
                            <div class="form-group @error('categories') has-error @enderror">
                                <label class="control-label" for="categories">{{ __('labels.create_form.category') }}</label>
                                <div>

                                    @foreach ($categories_select as $key =>$value)
                                        <div class="checkbox-inline">
                                            <label>
                                                <input  type="checkbox"
                                                        name = "categories[]"
                                                        value = "{{$key}}"
                                                        @if( old('categories') && in_array( $key, old('categories') )) checked @endif >
                                                        {{$value}}
                                            </label>
                                        </div>
                                    @endforeach

                                    @if($errors->has('categories'))
                                        <span class="help-block">{{$errors->first('categories')}}</span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-default"> {{ __('labels.commons.movie_submit') }} </button>
                                <a href="{{url('admin-movies-managment/movies')}}" class="btn btn-danger"> {{ __('labels.commons.back') }} </a>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
@endsection

resources/views/admin/movies/details.blade.php
@extends('layouts.admin-app')

@section('content')
    <div class="container">
        <div class="row">
            @include('components.message')
            <div class="col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading"> {{$movie->name}}</div>
                    <div class="panel-body">
                    @foreach( $movie->categories as $category )
                    <li class="list-group-item">
                        <strong> {{$category->name}} </strong> </br>
                    </li>
                    @endforeach
                    </div>
                    <div class="panel-footer">
                        <a href="{{ route('admin.movies.index') }}" class="btn btn-danger"> Indietro </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/movies/edit.blade.php
@extends('layouts.admin-app')
@section('content')
            <div class="container">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @include('components.message')
                <div class="row">
                    <div class="col-xs-12"> <!-- [ 'movie' => $movie->id ] -->
                        <form method="POST" action="{{route('admin.movies.update', $movie->id )}}"> <!-- 'movie' lo hai passato con il compact  -->
                            @csrf
                            @method('patch')
                            <div class="form-group @error('name') has-error @enderror">
                                <label class="control-label" for="movie-title">{{ __('labels.create_form.movie_name') }}</label>
                                <input type="text" class="form-control" id="movie-title" name="name" value="{{old('name') ? old('name') : $movie->name}}">
                                @if($errors->has('name'))
                                    <span class="help-block">{{$errors->first('name')}}</span>
                                @endif
                            </div>

                            <div class="form-group  @error('code') has-error @enderror">
                                <label class="control-label" for="movie-code">{{ __('labels.create_form.movie_code') }}</label>
                                <input readonly disabled type="text" class="form-control" id="movie-code" name="code" value="{{ $movie->code }}">
                                @if($errors->has('code'))
                                    <span class="help-block">{{$errors->first('code')}}</span>
                                @endif
                            </div>
                            <div class="form-group  @error('duration') has-error @enderror">
                                <label class="control-label" for="movie-duration">{{ __('labels.create_form.movie_duration') }}</label>
                                <input type="text" class="form-control" id="movie-duration" name="duration" value="{{old('duration') ? old('duration') : $movie->duration}}">
                                @if($errors->has('duration'))
                                    <span class="help-block">{{$errors->first('duration')}}</span>
                                @endif
                            </div>

                            <div class="form-group  @error('cover_path') has-error @enderror">
                                <label class="control-label" for="movie-cover">{{ __('labels.create_form.movie_cover') }}</label>
                                <input type="text" class="form-control" id="movie-cover" name="cover_path" value="{{old('cover_path') ? old('cover_path') : $movie->cover_path}}">
                                @if($errors->has('cover_path'))
                                    <span class="help-block">{{$errors->first('cover_path')}}</span>
                                @endif
                            </div>

                            <div class="form-group @error('categories') has-error @enderror">
                                <label class="control-label" for="categories">{{ __('labels.create_form.category') }}</label>
                                <div>
                                    @foreach ($categories as $category)
                                        @if(old('categories'))
                                            <div class="checkbox-inline">
                                                <label>
                                                    <input  type="checkbox"
                                                            name = "categories[]"
                                                            value = "{{$category->id}}"
                                                            @if( in_array( $category->id, old('categories') )) checked @endif >
                                                            {{$category->name}}
                                                </label>
                                            </div>
                                        @else

                                            @php
                                                $found = false;
                                                $checked ='';
                                            @endphp

                                            @foreach ($movie->categories as $movie_category)
                                                @if($movie_category->id === $category->id && !$found)
                                                    @php
                                                        $found = true;
                                                        $checked ='checked';
                                                    @endphp
                                                @endif
                                            @endforeach

                                                <div class="checkbox-inline">
                                                    <label>
                                                        <input  type="checkbox"
                                                                name = "categories[]"
                                                                value = "{{$category->id}}"
                                                                {{$checked}}> {{$category->name}}
                                                    </label>
                                                </div>

                                        @endif
                                    @endforeach
                                    @if($errors->has('categories'))
                                        <span class="help-block">{{$errors->first('categories')}}</span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-default"> {{ __('labels.commons.update') }} </button>
                                <a href="{{url('admin-movies-managment/movies')}}" class="btn btn-danger"> {{ __('labels.commons.back') }} </a>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
@endsection

resources/views/admin/movies/list.blade.php
@extends('layouts.admin-app')

@section('content')
    <div class="container">
        <div class="row">
            @include('components.message') {{--}} IMPORTANT{{--}}
            <div class="col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading"> List Film</div>
                    <div class="panel-body"> <!-- Esiste un altro ciclo per laravel ovvero il forelse, non mi piace LEZIONE 26 40MIN -->
                    @if(count($movies) > 0 )
                        <ul class="list-group">
                            @foreach($movies as $movie)
                                <li class="list-group-item">
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="media">
                                                <div class="media-left">
                                                    <img class="media-object" width="150" src="{{ asset( 'storage/' . $movie->cover_path ) }}" alt="...">
                                                </div>
                                                <div class="media-body">
                                                    <div class="row">
                                                        <div class="col-xs-12 col-md-8">
                                                            {{$movie->name}} <span class="badge"> {{ $movie->categories_count}}</span>
                                                        </div> <!-- [ 'movie' => $movie->id ] -->
                                                        <div class="col-xs-12 col-md-4 text-right">

                                                            <a href="{{ route( 'admin.movies.edit', $movie->id ) }}" class="btn btn-primary movies-list-action">
                                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                                            </a>

                                                            <a href="{{route('admin.movies.show', $movie->id)}}" class="btn btn-success movies-list-action">
                                                                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                            </a>
                                                            <!-- Delete funziona solo con il form-->
                                                            <form style=" display:inline;" method="POST" action="{{route('admin.movies.destroy', $movie->id )}}"> <!-- 'movie' lo hai passato con il compact  -->
                                                                @csrf
                                                                @method('delete')
                                                                <button type="submit"  class="btn btn-danger movies-list-action">
                                                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                                </button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    @else
                        <div class="alert alert-warning" role="alert">
                            Spiacenti non ci sono film nella base dati,
                            <a href=""> clicca qua per inserire il tup primo film </a>
                        </div>
                    @endif
                    </div>
                    <div class="panel-footer">
                        <!-- se ti stai chidendo perchè hanno lo stesso url è perchè esso cambia a secondo della richiesta -->
                        <a href="{{url('admin-movies-managment/movies/create')}}" class="btn btn-primary"> Aggiungi un film </a>
                        <a href="" class="btn btn-danger"> Indietro </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection