routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersController;


Auth::routes(
    [ //php artisan route:clear
        'verify'          => true, //attiva l'email di verifica se clicci nell'email che arriva su mailtrap l'account di verifica risulterà attivo su SQL
        // 'register'       => true, //attiva la registrazione
        // 'reset'          => false,
    ] );

Route::get('/', 'SiteController@index')->name('home');

Route::get('/contact-us', 'SiteController@contacts')->name('contacs-us');

Route::get('/entity/{id}/{name}/{filter?}', 'SiteController@test'); // scrivili nella barra del browser il punto interrogativo sta come opzionale

// Route::resource('movies', 'Admin\AdminMoviesController'); //O cosi' nel secondo parametro è già impostata la cartella controllers

Route::prefix('admin-movies-managment')->namespace('Admin')->name('admin.')->middleware('can:can-admin')->group( function ()
{
    Route::resource('movies', 'AdminMoviesController'); // in AdminMoviesManagmetn hai le funzioni pubblice, create,show,destroy. Il metodo resource crea quelle rotte
});


Route::prefix('admin-users-managment')->namespace('Admin')->name('admin.')->middleware('can:can-admin')->group( function () // per poter utilizzare can-admin devi andare in authserviceprovider nella cartella providers
{
    Route::resource('user', 'AdminUserController')->except(['create','store']);
    Route::get('user/{user}/restore','AdminUserController@restore')->name('user.restore');
});


Route::get('/test', 'TestController@index')->middleware('verified');

Route::get('/profile', 'UsersController@profile')->name('profile');
Route::patch('/update-profile', 'UsersController@profileUpdate')->name('update-profile');
Route::delete('/delete-profile', 'UsersController@deleteProfile')->name('delete-profile');

app/Models/User.php
<?php

namespace App\Models;

use app\Events\UserUpdated;
use app\Events\UserDeleted;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes; //lo hai aggiunto tu per implementare il soft deleting e poi devi fare la migrazione per aggiungere la colonna
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail // hai messo u implements MustVerifyEmail per riuscire a mandare un email
{
    use Notifiable; // se c'è questo trait puoi inviargli le email
    use SoftDeletes; //lo hai aggiunto tu per implementare il soft deleting e poi devi fare la migrazione per aggiungere la colonna

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role','last_login'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */

     protected $with =
     [
         'details',
     ];
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function details()
    {
        return $this->hasOne('App\Models\UserDetails');
    }

    public function userRole()
    {
        return $this->belongsTo('App\Models\Role','role','id');
    }

    public function scopeActive($query)
    {
        return $query->where('email_verified_at','<>', null );
    }

    public function scopeNotactive($query)
    {
        return $query->where('email_verified_at', null );
    }

    public function scopeStatus($query,$status) // il primo parametro è già implementato. Gli scope servono per richiamare le query, in modo da non doverle scrivere piu' volte
    {
        if($status === true)
        {
            return $query->whereNotNull('email_verified_at' ); // $query->where('email_verified_at','<>', null );
        }
        else
        {
            return $query->whereNull('email_verified_at');
        }
    }
    public function hasRole( $role) // questo serve solo per i gate, devi implementare questo, poi quello i nauthserviceproviders e poi il middleware in web routes
    {
        return $this->userRole->code === $role;
    }

    /*
    protected $dispatchesEvents =
    [
        'updated'       => UserUpdated::class,
        'deleted'       => UserDeleted::class
    ]; */
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use illuminate\Support\Facades\Auth;

class UsersController extends Controller
{

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */

     /* Non puoi accedere alla rotta se l'utente è sloggato
     public function __construct()
     {
         $this->middleware('auth');
     }
     */

     public function profile()
     {
         $user = Auth::user(); //per vedere se sei loggato

         return view('users.profile',compact('user'));
     }

     public function profileUpdate(Request $request)
     {
        $new_name = $request->get('name');
        if($new_name)
        {
            $user = Auth::user();
            $user->update(['name' => $new_name]);
            return view('users.profile',compact('user'));
        }
        else
        {
            dd('errore');
        }
     }

     public function deleteProfile(Request $request)
     {
        $user = Auth::user();
        $user->delete();

        auth()->logout();
        return redirect (route('login'));

     }

}

resources/views/admin/users/components/users-list-item.blade.php
<li class="list-group-item ">
    <div class="row">
        <div class="col-xs-12 col-md-8">
            {{$user->name}}
            <br>
            {{$user->email}}
        </div>
        <div class="text-right col-xs-12 col-md-4">

            <a href=" " class="btn btn-primary">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>

            <a href="{{route('admin.user.show', $user->id)}}" class="btn btn-success">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
            </a>

            @if($user->trashed())
                <a href="{{ route('admin.user.restore',$user->id) }}" class="btn btn-info">
                    <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
                </a>

                <form style=" display:inline;" method="POST" action="{{route('admin.user.destroy', $user->id )}}">

                    @csrf
                    @method('delete')

                    <button type="submit"  class="btn btn-danger" name="delete_action" value="d">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>

                </form>
            @else
            <form style=" display:inline;" method="POST" action="{{route('admin.user.destroy', $user->id )}}">
                @csrf
                @method('delete')
                <button type="submit"  class="btn btn-danger" name="delete_action" value="t">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </button>
            </form>
            @endif
        </div>
    </div>
</li>

resources/views/admin/users/components/users-list-paginator.blade.php
@if ($paginator->hasPages())
    <ul class="pagination" role="navigation">
        {{-- Previous Page Link --}}
        @if ($paginator->onFirstPage()) <!-- insomma, hai capito come funziona, ricordati che sei un genio a capire querste cose -->
            <li class="page-item disabled"> <!-- questo è un quadratino con un numero rsaquo e lsaquo sono le freccette destra e sinistra -->
                <span class="page-link" aria-hidden="true">&lsaquo;&lsaquo;</span>
            </li>
            <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.previous')">
                <span class="page-link" aria-hidden="true">&lsaquo;</span>
            </li>
        @else
            <li class="page-item"> <!-- questo è un quadratino con un numero rsaquo e lsaquo sono le freccette destra e sinistra -->
                <a class="page-link" href="{{ $paginator->url( 1 ) }}" rel="first" aria-label="@lang('pagination.first')">&lsaquo;&lsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{ $paginator->previousPageUrl() }}" rel="prev" aria-label="@lang('pagination.previous')">&lsaquo;</a>
            </li>
        @endif

        {{-- Pagination Elements --}}
        @foreach ($elements as $element)
            {{-- "Three Dots" Separator --}}
            @if (is_string($element))
                <li class="page-item disabled" aria-disabled="true"><span class="page-link">{{ $element }}</span></li>
            @endif

            {{-- Array Of Links --}}
            @if (is_array($element))
                @foreach ($element as $page => $url)
                    @if ($page == $paginator->currentPage())
                        <li class="page-item active" aria-current="page"><span class="page-link">{{ $page }}</span></li>
                    @else
                        <li class="page-item"><a class="page-link" href="{{ $url }}">{{ $page }}</a></li>
                    @endif
                @endforeach
            @endif
        @endforeach

        {{-- Next Page Link --}}
        @if ($paginator->hasMorePages())
            <li class="page-item">
                <a class="page-link" href="{{ $paginator->nextPageUrl() }}" rel="next" aria-label="@lang('pagination.next')">&rsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{ $paginator->url( $paginator->lastPage() ) }}" rel="last" aria-label="@lang('pagination.last')">&rsaquo;&rsaquo;</a>
            </li>
        @else
            <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.next')">
                <span class="page-link" aria-hidden="true">&rsaquo;</span>
            </li>
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&rsaquo;&rsaquo;</span>
            </li>
        @endif
    </ul>
@endif